services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dc_payment_gateway
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ENV: development
      SERVER_PORT: ":8080"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: dc_payment_gateway
      DB_SSLMODE: disable
      EXPRESSPAY_LOGIN: "21950"
      EXPRESSPAY_PASSWORD: "147521"
    ports:
      - "8080:8080"